"""Storage adapter protocol.

Track A (backend core) owns this file. Track B owns the concrete implementations
(``local.py``, ``s3.py``). Each implementation module must expose::

    def create_adapter(settings: Settings) -> StorageAdapter: ...

``app.api.deps.get_storage_adapter`` imports the module named by ``STORAGE_PROVIDER`` and
calls that factory.

Keys are opaque, slash-separated, and generated by the service layer
(``resumes/<lead-id>/<random>.<ext>``). Implementations must never expose a raw
filesystem path or bucket URL to callers.
"""

from collections.abc import AsyncIterator
from typing import Protocol


class StorageAdapter(Protocol):
    async def put(self, key: str, data: bytes, content_type: str) -> None:
        """Store ``data`` under ``key``, overwriting any existing object."""
        ...

    async def delete(self, key: str) -> None:
        """Remove ``key``. Must not raise if the key is missing."""
        ...

    def stream(self, key: str) -> AsyncIterator[bytes]:
        """Yield the object's bytes in chunks. Raise ``KeyError`` if the key is missing."""
        ...

    async def presigned_url(self, key: str, *, expires_in: int) -> str | None:
        """Return a time-limited URL for direct download, or ``None`` if the backend
        cannot produce one (local disk). The API streams the object in that case."""
        ...
